version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    post_checkout:
      - echo "dummy"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
formats: all

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
    - requirements: requirements/runtime.txt
