FROM paddlepaddle/paddle:3.0.0rc1-gpu-cuda12.3-cudnn9.0-trt8.6

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV arch=x86_64

# default shell bash
ENV SHELL=/bin/bash


ENV PATH /usr/local/bin:$PATH
ENV GPG_KEY A035C8C19219BA821ECEA86B64E628F8D684696D

SHELL ["/bin/bash", "-c"]

COPY docker/scripts/modelscope_env_init.sh /usr/local/bin/ms_env_init.sh
RUN apt-get update && \
    apt-get install -y libsox-dev unzip libaio-dev zip iputils-ping telnet sudo git net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# set link for python
RUN sudo ln -s /usr/bin/python3 /usr/local/bin/python


{extra_content}

# Install modelscope[datasets]
RUN pip install 'modelscope[datasets]' -U && pip cache purge

ARG CUR_TIME={cur_time}
RUN echo $CUR_TIME


ENV SETUPTOOLS_USE_DISTUTILS=stdlib
ENV VLLM_USE_MODELSCOPE=True
ENV LMDEPLOY_USE_MODELSCOPE=True
ENV MODELSCOPE_CACHE=/mnt/workspace/.cache/modelscope/hub
