PYTHONPATH=. torchrun examples/pytorch/stable_diffusion/finetune_stable_diffusion.py \
    --finetune_mode 'dreambooth' \
    --model 'AI-ModelScope/stable-diffusion-v1-5' \
    --model_revision 'v1.0.4' \
    --instance_prompt 'a photo of sks dog' \
    --with_prior_preservation false \
    --prior_loss_weight 1.0 \
    --class_prompt 'a photo of dog' \
    --num_class_images 200 \
    --sample_batch_size 4 \
    --instance_prompt "a photo of sks dog" \
    --pretrained_model_name_or_path 'runwayml/stable-diffusion-v1-5' \
    --class_data_dir '/tmp/class_data' \
    --work_dir './tmp/dreambooth_tuning' \
    --train_dataset_name 'buptwq/lora-stable-diffusion-finetune-dog' \
    --max_epochs 400 \
    --save_ckpt_strategy 'by_epoch' \
    --logging_interval 100 \
    --train.dataloader.workers_per_gpu 0 \
    --evaluation.dataloader.workers_per_gpu 0 \
    --train.optimizer.lr 5e-6 \
    --use_model_config true