# Copyright (c) Alibaba, Inc. and its affiliates.

emotion_types = [
    'emotion_none',
    'emotion_neutral',
    'emotion_angry',
    'emotion_disgust',
    'emotion_fear',
    'emotion_happy',
    'emotion_sad',
    'emotion_surprise',
    'emotion_calm',
    'emotion_gentle',
    'emotion_relax',
    'emotion_lyrical',
    'emotion_serious',
    'emotion_disgruntled',
    'emotion_satisfied',
    'emotion_disappointed',
    'emotion_excited',
    'emotion_anxiety',
    'emotion_jealousy',
    'emotion_hate',
    'emotion_pity',
    'emotion_pleasure',
    'emotion_arousal',
    'emotion_dominance',
    'emotion_placeholder1',
    'emotion_placeholder2',
    'emotion_placeholder3',
    'emotion_placeholder4',
    'emotion_placeholder5',
    'emotion_placeholder6',
    'emotion_placeholder7',
    'emotion_placeholder8',
    'emotion_placeholder9',
]
